pretrained_path: ??? #set this parameter via CLI in eval_pqn.py
num_samples: 1000
use_last: False

#you can also rewrite any parameter from training config in this config:
seed: 42
device: 'cuda:0'
random_sampling: false #choice: if true then samples are choosen randomly
envs:
  num_sentences: 50
  #max_steps: 6
  #max_chunks_count: 2000





