defaults:
  - envs: babilong 
  - feedback: defaults
  - algo: pqn
  - logger: logging
  - _self_

seed: 42
device: 'cuda:0'
learning_start: 200
steps_count: 50_000
batch_size: 32
accumulate_grads: 2
eval_interval: 300
eval_episodes: 300
envs_parallel: 1
max_action_length: 64
